# Generated by Django 4.0.6 on 2022-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preganancy',
            name='pregnancy',
            field=models.CharField(max_length=500),
        ),
    ]
