# Generated by Django 4.0.6 on 2022-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentextra_dose_studentextra_kids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preganancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacctype', models.CharField(choices=[('covishield', 'covishield'), ('covaxin', 'covaxin'), ('sputnik', 'sputnik')], default='covishield', max_length=10)),
                ('vaccdate', models.CharField(max_length=40, null=True)),
                ('dose', models.CharField(choices=[('first', 'first'), ('second', 'second')], default='first', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='vaccdate',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='vacctype',
        ),
    ]
